### ISSUE TITLE
zh_TW_c4  404 error

### ISSUE THREAD

**Issue by me-v2** [MiuLab/Taiwan-LLM#20]
https://huggingface.co/datasets/yentinglin/zh_TW_c4

**Comment by lianghsun** [comment]
It seems that the original author has taken down these two datasets.

**Comment by adamlin120** [comment]
Due to legal concerns raised by our legal advisors regarding copyrighted material, we've temporarily removed the datasets. We're actively seeking further opinions and hope to make the training datasets available again soon. Rest assured, the models are not affected by this issue.

經過專業律師的法律建議，我們暫時將有版權疑慮的資料集下架。我們會積極尋求更多的法律意見，希望能儘快重新上架這些訓練資料集。模型本身並無此疑慮，請大家放心。
